// NexiaCompiler v2.0 — SDK Header Generator
// Ported from SdkHeaders.cs — FULL implementation
#include "sdk_headers.h"
#include <fstream>
#ifdef _WIN32
#include <direct.h>
#define MKDIR(dir) _mkdir(dir)
#else
#include <sys/stat.h>
#define MKDIR(dir) mkdir(dir, 0755)
#endif

namespace nexia {

SdkHeaderGenerator::SdkHeaderGenerator(const std::string& dir) : output_dir_(dir) {}

void SdkHeaderGenerator::write_header(const std::string& name, const std::string& content) {
    std::ofstream f(output_dir_ + "/" + name);
    if (f) f << "// Auto-generated by NexiaCompiler v2.0\n// Xbox 360 SDK stub header\n#pragma once\n\n" << content;
}

std::vector<std::string> SdkHeaderGenerator::get_header_names() {
    return {"xtypes.h","xtl.h","xboxmath.h","d3d9.h","xaudio2.h","xinput.h","xui.h","xam.h"};
}

void SdkHeaderGenerator::generate_all() {
    // Create output directory if needed
    MKDIR(output_dir_.c_str());
    write_header("xtypes.h", generate_xtypes());
    write_header("xtl.h", generate_xtl());
    write_header("xboxmath.h", generate_xbox_math());
    write_header("d3d9.h", generate_d3d9());
    write_header("xaudio2.h", generate_xaudio2());
    write_header("xinput.h", generate_xinput());
    write_header("xui.h", generate_xui());
    write_header("xam.h", generate_xam());
    // stdafx.h — the precompiled header that most Xbox 360 projects use
    write_header("stdafx.h", "#include \"xtl.h\"\n#include \"xboxmath.h\"\n#include \"d3d9.h\"\n");
}

std::string SdkHeaderGenerator::generate_xtypes() {
    return R"(
typedef unsigned char BYTE;
typedef unsigned short WORD;
typedef unsigned long DWORD;
typedef unsigned long ULONG;
typedef long LONG;
typedef int BOOL;
typedef int INT;
typedef unsigned int UINT;
typedef short SHORT;
typedef unsigned short USHORT;
typedef char CHAR;
typedef unsigned char UCHAR;
typedef float FLOAT;
typedef void VOID;
typedef void* PVOID;
typedef void* LPVOID;
typedef const void* LPCVOID;
typedef char* LPSTR;
typedef const char* LPCSTR;
typedef wchar_t* LPWSTR;
typedef const wchar_t* LPCWSTR;
typedef DWORD* LPDWORD;
typedef BYTE* LPBYTE;
typedef int HRESULT;
typedef void* HANDLE;
typedef unsigned long long ULONGLONG;
typedef long long LONGLONG;
typedef unsigned long long UINT64;
typedef long long INT64;
typedef unsigned int UINT32;
typedef int INT32;
typedef unsigned short UINT16;
typedef short INT16;
typedef unsigned char UINT8;
typedef char INT8;
typedef unsigned int SIZE_T;

#define TRUE 1
#define FALSE 0
#define NULL 0
#define SUCCEEDED(hr) ((HRESULT)(hr) >= 0)
#define FAILED(hr) ((HRESULT)(hr) < 0)
#define S_OK ((HRESULT)0)
#define E_FAIL ((HRESULT)0x80004005)
#define E_OUTOFMEMORY ((HRESULT)0x8007000E)
#define E_INVALIDARG ((HRESULT)0x80070057)
#define INFINITE 0xFFFFFFFF
#define MAX_PATH 260

struct GUID { DWORD Data1; WORD Data2; WORD Data3; BYTE Data4[8]; };
typedef GUID IID;
typedef GUID CLSID;
#define DEFINE_GUID(name, l, w1, w2, b1, b2, b3, b4, b5, b6, b7, b8)

struct RECT { LONG left; LONG top; LONG right; LONG bottom; };
struct POINT { LONG x; LONG y; };
struct SIZE { LONG cx; LONG cy; };

struct LARGE_INTEGER {
    DWORD LowPart;
    LONG HighPart;
    LONGLONG QuadPart;
};
struct ULARGE_INTEGER {
    DWORD LowPart;
    DWORD HighPart;
    ULONGLONG QuadPart;
};

typedef struct _FILETIME { DWORD dwLowDateTime; DWORD dwHighDateTime; } FILETIME;
typedef struct _SYSTEMTIME { WORD wYear; WORD wMonth; WORD wDayOfWeek; WORD wDay; WORD wHour; WORD wMinute; WORD wSecond; WORD wMilliseconds; } SYSTEMTIME;

struct CRITICAL_SECTION { void* p; };
struct OVERLAPPED { ULONG Internal; ULONG InternalHigh; DWORD Offset; DWORD OffsetHigh; HANDLE hEvent; };

// C runtime functions
void* memset(void* dest, int value, unsigned int size);
void* memcpy(void* dest, const void* src, unsigned int size);
void* memmove(void* dest, const void* src, unsigned int size);
int memcmp(const void* s1, const void* s2, unsigned int size);
unsigned int strlen(const char* str);
char* strcpy(char* dest, const char* src);
int strcmp(const char* s1, const char* s2);
float fmodf(float x, float y);
float sqrtf(float x);
float sinf(float x);
float cosf(float x);
float tanf(float x);
int abs(int x);
int printf(const char* fmt, ...);
int sprintf(char* buf, const char* fmt, ...);
void* malloc(unsigned int size);
void free(void* ptr);

#define ZeroMemory(dest, size) memset((dest), 0, (size))
#define RtlZeroMemory(dest, size) memset((dest), 0, (size))
#define CopyMemory(dest, src, size) memcpy((dest), (src), (size))
#define RtlCopyMemory(dest, src, size) memcpy((dest), (src), (size))
#define FillMemory(dest, size, val) memset((dest), (val), (size))
#define RtlFillMemory(dest, size, val) memset((dest), (val), (size))

// Compiler intrinsics — mapped to no-ops or inline equivalents for NexiaCompiler
#define __debugbreak() ((void)0)
#define __noop ((void)0)
#define __assume(x) ((void)0)

// PPC floating-point conversion intrinsics
// __fctidz: float to int64 (truncate) — cast to int
// __fcfid: int64 to float — cast to float
#define __fctidz(x) ((long long)(x))
#define __fcfid(x) ((float)(x))

// SSE intrinsics mapped to scalar equivalents (Xbox 360 uses VMX128, but for
// the compiler these just need to resolve — the codegen handles vector ops)
typedef struct { float x; float y; float z; float w; } __m128;
#define _mm_set_ps1(v) ((__m128){(v),(v),(v),(v)})
#define _mm_set1_ps(v) ((__m128){(v),(v),(v),(v)})
#define _mm_add_ps(a,b) ((__m128){(a).x+(b).x,(a).y+(b).y,(a).z+(b).z,(a).w+(b).w})
#define _mm_sub_ps(a,b) ((__m128){(a).x-(b).x,(a).y-(b).y,(a).z-(b).z,(a).w-(b).w})
#define _mm_mul_ps(a,b) ((__m128){(a).x*(b).x,(a).y*(b).y,(a).z*(b).z,(a).w*(b).w})
#define _mm_div_ps(a,b) ((__m128){(a).x/(b).x,(a).y/(b).y,(a).z/(b).z,(a).w/(b).w})

#ifndef min
#define min(a,b) ((a) < (b) ? (a) : (b))
#endif
#ifndef max
#define max(a,b) ((a) > (b) ? (a) : (b))
#endif
)";
}

std::string SdkHeaderGenerator::generate_xtl() {
    return R"(
#include "xtypes.h"
void OutputDebugStringA(LPCSTR lpOutputString);
void OutputDebugStringW(LPCWSTR lpOutputString);
#define OutputDebugString OutputDebugStringA
DWORD GetTickCount();
void Sleep(DWORD dwMilliseconds);
BOOL QueryPerformanceCounter(LARGE_INTEGER* lpPerformanceCount);
BOOL QueryPerformanceFrequency(LARGE_INTEGER* lpFrequency);
HANDLE CreateThread(void* lpThreadAttributes, SIZE_T dwStackSize, void* lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
void ExitThread(DWORD dwExitCode);
DWORD WaitForSingleObject(HANDLE hHandle, DWORD dwMilliseconds);
void InitializeCriticalSection(CRITICAL_SECTION* lpCriticalSection);
void EnterCriticalSection(CRITICAL_SECTION* lpCriticalSection);
void LeaveCriticalSection(CRITICAL_SECTION* lpCriticalSection);
void DeleteCriticalSection(CRITICAL_SECTION* lpCriticalSection);
HANDLE CreateFileA(LPCSTR lpFileName, DWORD dwDesiredAccess, DWORD dwShareMode, void* lpSecurityAttributes, DWORD dwCreationDisposition, DWORD dwFlagsAndAttributes, HANDLE hTemplateFile);
#define CreateFile CreateFileA
BOOL ReadFile(HANDLE hFile, LPVOID lpBuffer, DWORD nNumberOfBytesToRead, LPDWORD lpNumberOfBytesRead, OVERLAPPED* lpOverlapped);
BOOL WriteFile(HANDLE hFile, LPCVOID lpBuffer, DWORD nNumberOfBytesToWrite, LPDWORD lpNumberOfBytesWritten, OVERLAPPED* lpOverlapped);
BOOL CloseHandle(HANDLE hObject);
DWORD GetLastError();
void* XMemAlloc(SIZE_T dwSize, DWORD dwAllocAttributes);
void XMemFree(PVOID pAddress, DWORD dwAllocAttributes);
)";
}

std::string SdkHeaderGenerator::generate_xbox_math() {
    return R"(
#include "xtypes.h"

#define XM_PI 3.14159265358979323846f
#define XM_2PI 6.28318530717958647692f
#define XM_PIDIV2 1.57079632679489661923f
#define XM_PIDIV4 0.78539816339744830961f

typedef struct __vector4 { float x, y, z, w; } __vector4;
typedef __vector4 XMVECTOR;
struct XMFLOAT2 { float x; float y; };
struct XMFLOAT3 { float x; float y; float z; };
struct XMFLOAT4 { float x; float y; float z; float w; };
struct XMFLOAT4X4 { float m[4][4]; };
struct XMMATRIX { XMVECTOR r[4]; };
typedef const XMVECTOR FXMVECTOR;
typedef const XMMATRIX FXMMATRIX;

XMVECTOR XMVectorSet(float x, float y, float z, float w);
XMVECTOR XMVectorZero();
XMVECTOR XMVectorAdd(FXMVECTOR V1, FXMVECTOR V2);
XMVECTOR XMVectorSubtract(FXMVECTOR V1, FXMVECTOR V2);
XMVECTOR XMVectorMultiply(FXMVECTOR V1, FXMVECTOR V2);
XMVECTOR XMVectorScale(FXMVECTOR V, float ScaleFactor);
XMVECTOR XMVector3Dot(FXMVECTOR V1, FXMVECTOR V2);
XMVECTOR XMVector3Cross(FXMVECTOR V1, FXMVECTOR V2);
XMVECTOR XMVector3Normalize(FXMVECTOR V);
float XMVectorGetX(FXMVECTOR V);
float XMVectorGetY(FXMVECTOR V);
float XMVectorGetZ(FXMVECTOR V);
XMMATRIX XMMatrixIdentity();
XMMATRIX XMMatrixMultiply(FXMMATRIX M1, FXMMATRIX M2);
XMMATRIX XMMatrixTranspose(FXMMATRIX M);
XMMATRIX XMMatrixInverse(XMVECTOR* pDeterminant, FXMMATRIX M);
XMMATRIX XMMatrixLookAtLH(FXMVECTOR EyePosition, FXMVECTOR FocusPosition, FXMVECTOR UpDirection);
XMMATRIX XMMatrixPerspectiveFovLH(float FovAngleY, float AspectRatio, float NearZ, float FarZ);
XMMATRIX XMMatrixOrthographicLH(float ViewWidth, float ViewHeight, float NearZ, float FarZ);
XMMATRIX XMMatrixTranslation(float OffsetX, float OffsetY, float OffsetZ);
XMMATRIX XMMatrixScaling(float ScaleX, float ScaleY, float ScaleZ);
XMMATRIX XMMatrixRotationX(float Angle);
XMMATRIX XMMatrixRotationY(float Angle);
XMMATRIX XMMatrixRotationZ(float Angle);
XMMATRIX XMMatrixRotationAxis(FXMVECTOR Axis, float Angle);
void XMStoreFloat4x4(XMFLOAT4X4* pDestination, FXMMATRIX M);
XMMATRIX XMLoadFloat4x4(const XMFLOAT4X4* pSource);

// Operator overloads for XMMATRIX
XMMATRIX operator*(FXMMATRIX M1, FXMMATRIX M2);

// Scalar helpers
#define XMMax(a,b) ((a) > (b) ? (a) : (b))
#define XMMin(a,b) ((a) < (b) ? (a) : (b))
#define XMScalarSin(x) sinf(x)
#define XMScalarCos(x) cosf(x)
#define XMConvertToRadians(x) ((x) * 0.01745329252f)
#define XM_PI 3.14159265358979323846f
#define XM_2PI 6.28318530717958647692f
#define XM_PIDIV2 1.57079632679489661923f
#define XM_PIDIV4 0.78539816339744830962f
)";
}

std::string SdkHeaderGenerator::generate_d3d9() {
    return R"(
#include "xtypes.h"
#include "xboxmath.h"

// Forward declarations
struct IDirect3D9;
struct IDirect3DDevice9;
struct IDirect3DTexture9;
struct IDirect3DVertexBuffer9;
struct IDirect3DIndexBuffer9;
struct IDirect3DVertexShader9;
struct IDirect3DPixelShader9;
struct IDirect3DVertexDeclaration9;
struct IDirect3DSurface9;
struct ID3DXBuffer;

// Xbox 360 typedefs
typedef IDirect3D9 Direct3D;
typedef IDirect3DDevice9 D3DDevice;
typedef IDirect3DVertexBuffer9 D3DVertexBuffer;
typedef IDirect3DIndexBuffer9 D3DIndexBuffer;
typedef IDirect3DTexture9 D3DTexture;
typedef IDirect3DVertexShader9 D3DVertexShader;
typedef IDirect3DPixelShader9 D3DPixelShader;
typedef IDirect3DVertexDeclaration9 D3DVertexDeclaration;
typedef IDirect3DSurface9 D3DSurface;

typedef DWORD D3DCOLOR;
#define D3DCOLOR_ARGB(a,r,g,b) ((D3DCOLOR)((((a)&0xff)<<24)|(((r)&0xff)<<16)|(((g)&0xff)<<8)|((b)&0xff)))
#define D3DCOLOR_XRGB(r,g,b) D3DCOLOR_ARGB(0xff,r,g,b)

#define D3DPT_POINTLIST 1
#define D3DPT_LINELIST 2
#define D3DPT_LINESTRIP 3
#define D3DPT_TRIANGLELIST 4
#define D3DPT_TRIANGLESTRIP 5
#define D3DPT_TRIANGLEFAN 6

#define D3DFMT_UNKNOWN 0
#define D3DFMT_A8R8G8B8 21
#define D3DFMT_X8R8G8B8 22
#define D3DFMT_R5G6B5 23
#define D3DFMT_D24S8 75
#define D3DFMT_LIN_A8R8G8B8 0x12

#define D3DPOOL_DEFAULT 0
#define D3DPOOL_MANAGED 1

#define D3DDEVTYPE_HAL 1
#define D3DDEVTYPE_REF 2

#define D3DSWAPEFFECT_DISCARD 1
#define D3DSWAPEFFECT_FLIP 2
#define D3DSWAPEFFECT_COPY 3

#define D3DCREATE_HARDWARE_VERTEXPROCESSING 0x00000040
#define D3DPRESENT_INTERVAL_ONE 0x00000001
#define D3DPRESENT_INTERVAL_IMMEDIATE 0x80000000

#define D3DDECLTYPE_FLOAT3 2
#define D3DDECLTYPE_D3DCOLOR 4
#define D3DDECLMETHOD_DEFAULT 0
#define D3DDECLUSAGE_POSITION 0
#define D3DDECLUSAGE_COLOR 10

struct D3DPRESENT_PARAMETERS {
    UINT BackBufferWidth; UINT BackBufferHeight; D3DFORMAT BackBufferFormat;
    UINT BackBufferCount; UINT MultiSampleType; DWORD MultiSampleQuality;
    UINT SwapEffect; HANDLE hDeviceWindow; BOOL Windowed;
    BOOL EnableAutoDepthStencil; D3DFORMAT AutoDepthStencilFormat;
    DWORD Flags; UINT FullScreen_RefreshRateInHz; UINT PresentationInterval;
};

struct D3DVIEWPORT9 { DWORD X; DWORD Y; DWORD Width; DWORD Height; float MinZ; float MaxZ; };
struct D3DVERTEXELEMENT9 { WORD Stream; WORD Offset; BYTE Type; BYTE Method; BYTE Usage; BYTE UsageIndex; };

struct XVIDEO_MODE { DWORD dwDisplayWidth; DWORD dwDisplayHeight; BOOL fIsInterlaced; BOOL fIsWideScreen; DWORD VideoStandard; };
void XGetVideoMode(XVIDEO_MODE* pVideoMode);

// ID3DXBuffer interface (simplified)
struct ID3DXBuffer {
    void* GetBufferPointer();
    DWORD GetBufferSize();
};

// IDirect3D9 interface (simplified)
struct IDirect3D9 {
    HRESULT CreateDevice(UINT Adapter, D3DDEVTYPE DeviceType, void* hFocusWindow, DWORD BehaviorFlags, D3DPRESENT_PARAMETERS* pPresentationParameters, IDirect3DDevice9** ppReturnedDeviceInterface);
};

// IDirect3DDevice9 interface (simplified)
struct IDirect3DDevice9 {
    HRESULT Clear(DWORD Count, const void* pRects, DWORD Flags, D3DCOLOR Color, float Z, DWORD Stencil);
    HRESULT SetVertexDeclaration(IDirect3DVertexDeclaration9* pDecl);
    HRESULT SetStreamSource(UINT StreamNumber, IDirect3DVertexBuffer9* pStreamData, UINT OffsetInBytes, UINT Stride);
    HRESULT SetVertexShader(IDirect3DVertexShader9* pShader);
    HRESULT SetPixelShader(IDirect3DPixelShader9* pShader);
    HRESULT SetVertexShaderConstantF(UINT StartRegister, const FLOAT* pConstantData, UINT Vector4fCount);
    HRESULT DrawPrimitive(D3DPRIMITIVETYPE PrimitiveType, UINT StartVertex, UINT PrimitiveCount);
    HRESULT Present(const void* pSourceRect, const void* pDestRect, void* hDestWindowOverride, const void* pDirtyRegion);
    HRESULT CreateVertexShader(const DWORD* pFunction, IDirect3DVertexShader9** ppShader);
    HRESULT CreatePixelShader(const DWORD* pFunction, IDirect3DPixelShader9** ppShader);
    HRESULT CreateVertexDeclaration(const D3DVERTEXELEMENT9* pVertexElements, IDirect3DVertexDeclaration9** ppDecl);
    HRESULT CreateVertexBuffer(UINT Length, DWORD Usage, DWORD FVF, D3DPOOL Pool, IDirect3DVertexBuffer9** ppVertexBuffer, void* pSharedHandle);
};

// IDirect3DVertexBuffer9 interface (simplified)
struct IDirect3DVertexBuffer9 {
    HRESULT Lock(UINT OffsetToLock, UINT SizeToLock, void** ppbData, DWORD Flags);
    HRESULT Unlock();
};

IDirect3D9* Direct3DCreate9(UINT SDKVersion);
#define D3D_SDK_VERSION 31
#define D3DDECL_END() {0xFF,0,0,0,0,0}

HRESULT D3DXCompileShader(LPCSTR pSrcData, UINT SrcDataLen, const void* pDefines, const void* pInclude, LPCSTR pFunctionName, LPCSTR pProfile, DWORD Flags, ID3DXBuffer** ppShader, ID3DXBuffer** ppErrorMsgs, void* ppConstantTable);

#define D3DUSAGE_WRITEONLY 0x00000008
#define D3DLOCK_NONE 0
#define D3DCLEAR_TARGET 0x00000001
#define D3DCLEAR_ZBUFFER 0x00000002
#define D3DCLEAR_STENCIL 0x00000004

// Xbox 360 GPU command buffer tag macros
// These build GPU command packet headers for the Xenos GPU
#define D3DTAG_INDEX(tag) (((tag) >> 0) & 0xFFFF)
#define D3DTAG_COUNT(tag) (((tag) >> 16) & 0x3FFF)
#define D3DTAG_START(base, count) (((base) & 0xFFFF) | (((count) & 0x3FFF) << 16) | (3 << 30))
#define D3DTAG_MASKENCODE(mask) ((mask) & 0xFFFF)

// GPU fetch constant conversion — these are hardware-specific register packing macros
// On real hardware these do bitfield manipulation for the Xenos GPU fetch constants
// In the compiler they're no-ops that pass through the structure
#define GPU_CONVERT_D3D_TO_HARDWARE_TEXTUREFETCHCONSTANT(d3d, hw) do { (void)(d3d); (void)(hw); } while(0)
#define GPU_CONVERT_D3D_TO_HARDWARE_VERTEXFETCHCONSTANT(d3d, hw) do { (void)(d3d); (void)(hw); } while(0)
#define GPU_CONVERT_D3D_TO_HARDWARE_BOOLFETCHCONSTANT(d3d, hw) do { (void)(d3d); (void)(hw); } while(0)
)";
}

std::string SdkHeaderGenerator::generate_xaudio2() {
    return R"(
#include "xtypes.h"
struct IXAudio2;
struct IXAudio2MasteringVoice;
struct IXAudio2SourceVoice;
struct WAVEFORMATEX { WORD wFormatTag; WORD nChannels; DWORD nSamplesPerSec; DWORD nAvgBytesPerSec; WORD nBlockAlign; WORD wBitsPerSample; WORD cbSize; };
struct XAUDIO2_BUFFER { UINT32 Flags; UINT32 AudioBytes; const BYTE* pAudioData; UINT32 PlayBegin; UINT32 PlayLength; UINT32 LoopBegin; UINT32 LoopLength; UINT32 LoopCount; void* pContext; };
HRESULT XAudio2Create(IXAudio2** ppXAudio2, UINT32 Flags, UINT32 XAudio2Processor);
#define WAVE_FORMAT_PCM 1
#define XAUDIO2_DEFAULT_PROCESSOR 0xFFFFFFFF
)";
}

std::string SdkHeaderGenerator::generate_xinput() {
    return R"(
#include "xtypes.h"
struct XINPUT_GAMEPAD { WORD wButtons; BYTE bLeftTrigger; BYTE bRightTrigger; SHORT sThumbLX; SHORT sThumbLY; SHORT sThumbRX; SHORT sThumbRY; };
struct XINPUT_STATE { DWORD dwPacketNumber; XINPUT_GAMEPAD Gamepad; };
struct XINPUT_VIBRATION { WORD wLeftMotorSpeed; WORD wRightMotorSpeed; };
DWORD XInputGetState(DWORD dwUserIndex, XINPUT_STATE* pState);
DWORD XInputSetState(DWORD dwUserIndex, XINPUT_VIBRATION* pVibration);
#define XINPUT_GAMEPAD_DPAD_UP 0x0001
#define XINPUT_GAMEPAD_DPAD_DOWN 0x0002
#define XINPUT_GAMEPAD_DPAD_LEFT 0x0004
#define XINPUT_GAMEPAD_DPAD_RIGHT 0x0008
#define XINPUT_GAMEPAD_START 0x0010
#define XINPUT_GAMEPAD_BACK 0x0020
#define XINPUT_GAMEPAD_LEFT_THUMB 0x0040
#define XINPUT_GAMEPAD_RIGHT_THUMB 0x0080
#define XINPUT_GAMEPAD_LEFT_SHOULDER 0x0100
#define XINPUT_GAMEPAD_RIGHT_SHOULDER 0x0200
#define XINPUT_GAMEPAD_A 0x1000
#define XINPUT_GAMEPAD_B 0x2000
#define XINPUT_GAMEPAD_X 0x4000
#define XINPUT_GAMEPAD_Y 0x8000
#define ERROR_SUCCESS 0
#define ERROR_DEVICE_NOT_CONNECTED 1167
)";
}

std::string SdkHeaderGenerator::generate_xui() { return "// XUI stubs\n#include \"xtypes.h\"\n"; }
std::string SdkHeaderGenerator::generate_xam() { return "// XAM stubs\n#include \"xtypes.h\"\n"; }

} // namespace nexia
